### ISSUE TITLE
Racket: passes locally, not online

### ISSUE THREAD

**Issue by p0w1nd** [exercism/racket-test-runner#28]
This exercise: https://exercism.org/tracks/racket/exercises/perfect-numbers

The below code passes the test on my local machine:

```racket
#lang racket

(provide classify)

(define (factors-of N)
  (for/list ([i (range 2 (add1 N))]
             #:when (zero? (modulo N i)))
    (quotient N i)))
   
(define (classify N)
  (define sum (for/sum ([i (factors-of N)]) i))
  (cond
    [(= sum N) 'perfect]
    [(> sum N) 'abundant]
    [else 'deficient]))
```
<img width="899" alt="Screen Shot 2021-09-19 at 15 01 48" src="https://user-images.githubusercontent.com/14937764/133920071-b892b10f-9940-4db1-839d-ad0c94060e11.png">

But produces an error like this on the website:

![Screen Shot 2021-09-18 at 22 06 35](https://user-images.githubusercontent.com/14937764/133920021-0528e772-27b9-43a2-9321-5cf4a71ec1dd.png)

**Comment by p0w1nd** [comment]
```The Docker image uses Racket 6.6 but I see the newest version is 8.2. Could that be the cause?```

Version 6.6 is quite old (July 2016) so I think it should be upgraded anyway. https://download.racket-lang.org/all-versions.html

**Comment by ErikSchierboom** [comment]
I'll look into it!

**Comment by ErikSchierboom** [comment]
PR submitted: #29

**Comment by p0w1nd** [comment]
SWEET!! :) Thanks everyone!

<img width="457" alt="Screen Shot 2021-09-30 at 20 49 30" src="https://user-images.githubusercontent.com/14937764/135467854-ebf49ef9-5c43-4e58-9309-3937f03fb548.png">
